### PR TITLE
Created an endpoint to retrieve list of user’s repos

### LINKED ISSUE #179: Create an endpoint to retrieve list of user’s repos
### Comments or additional Information
Give additional information or a  brief description of the Backend issue you wrote.

### PR DESCRIPTION
**Pull request by Nathan-Okolo**
**Before submitting your PR for review**

- Run `npm run eslint` to find errors in code syntax/format
- Run `npm run eslint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands
- Ensure you fix all merge conflicts before sending PR

**What does this PR do?**

Fixes #179 

Live Link
https://user-repo.herokuapp.com/api/repos/Nathan-Okolo

**Description of Task to be completed?**

This task was to create an endpoint where users can retrieve the list of their repos

**How should this be manually tested?**
https://user-repo.herokuapp.com/api/repos/Nathan-Okolo

**What is the link to the issue on Github?**

Issue #179

### CODE REVIEW

**Comment by Nathan-Okolo** [comment]
@alvacoder 
PLease Review My PR thank you

**Review by Evavic44 — APPROVED** [review]
Awesome. LGTM! 👍🏾

**Comment by claretnnamocha** [comment]
@Nathan-Okolo please resolve conflicts on your branch

**Comment by claretnnamocha** [comment]
@Nathan-Okolo please resolve conflicts on your branch

**Comment by Nathan-Okolo** [comment]
@claretnnamocha i have fixed the merge conflict thanks

**Comment by Nathan-Okolo** [comment]
Biko @Davien21 , @alvacoder , @Evavic44 make unna merge my code abegi before more conflict go day show

**Pull request merged**
