### PR TITLE
Implemented search bar for giphy

### PR DESCRIPTION
**Pull request by RinsolaO**
https://zuriplugin.vercel.app/

issue #314 https://github.com/zurichat/zc_plugin_tools/issues/314

### CODE REVIEW

**Comment by Davien21** [comment]
Hi. where is the search bar?

**Review by Evavic44 — COMMENTED** [review]
Thought the package-lock.json file should be gitignored?
It doesn't have to be ignored

**Comment by Davien21** [comment]
@Evavic44 - the package-lock.json doesn't have to be ignored

**Comment by Evavic44** [comment]
> 
> 
> @Evavic44 - the package-lock.json doesn't have to be ignored

Oh, okay boss.

**Comment by RinsolaO** [comment]
https://zuriplugin.vercel.app/ 

did you see this ?

**Pull request closed without merging**
