### PR TITLE
worked on issue number 179

### PR DESCRIPTION
**Pull request by Nathan-Okolo**
**Before submitting your PR for review**

- Run `npm run eslint` to find errors in code syntax/format
- Run `npm run eslint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands
- Ensure you fix all merge conflicts before sending PR

**What does this PR do?**

Fixes #issue_number (replace issue_number with the issue number this PR solves)

Summarise the main tasks handled in the pull request
Ans: Creating an enpoint that returns a user's github repo

**Description of Task to be completed?**

Describe (in detail) what the task completed in the pull request does as per the relevant task
Ans: this particular issue helps to get the repos of  the user

**How should this be manually tested?**

Give bullet point instructions on how to setup the code and test it manually (Assume no prior experience on JS or code)
Ans: localhost:3600/api/repos/:github-username

**Any background context you want to provide?**

Any pertinent information that should be considered?
Ans: None

**What is the link to the issue on Github?**

[Issue #176](https://github.com/zurichat/zc_plugin_tools/issues/176)

**Questions:**

If something is unclear or you want some questions to be addressed by your peers, mention them here
Ans: Non

### CODE REVIEW

**Comment by Nathan-Okolo** [comment]
issue#176

**Comment by Davien21** [comment]
1. Your issue number (176) is wrong.
2. the name of your **PR** is not describing what you did, so I don't understand - might have been okay if the correct issue was used though, but it wasn't
3. The answer to **How should this be manually tested** is not correct, i cannot see your localhost and **/repos** is an invalid route
4. You did not add any reviewer on this **PR**

**Comment by Nathan-Okolo** [comment]
thanks

**Comment by Davien21** [comment]
Dm me on slack, let's see what you're tryna do and we can work on it

**Pull request closed without merging**
