### PR TITLE
Implemented search bar

### PR DESCRIPTION
**Pull request by RinsolaO**
Issue #314

View here -> https://zuripluginn.vercel.app/giphy

@Johndiddles is my reviewer, but I am unable to add him

### CODE REVIEW

**Review by Johndiddles — APPROVED** [review]
@Davien21 
I have reviewed and all changes have been effected as earlier mentioned. The component is also available on the live link.

**Review by Evavic44 — APPROVED** [review]
LGTM. 👍🏾

**Comment by oscar-ekeyekwu** [comment]
@RinsolaO please what app or team is this PR meant for 

and please close this PR and send PR to the dev branch not main branch 

we cannot merge into main

**Comment by RinsolaO** [comment]
pr was to main branch not dev

**Pull request closed without merging**
