### PR TITLE
made gmail interface responsive

### LINKED ISSUE #449: Gmail - [FRONTEND ISSUE] - Make the gmail interface responsive
### Comments or additional Information
Give additional information or a  brief description of the Frontend issue you wrote.

### PR DESCRIPTION
**Pull request by chideranwafor**
What does this PR do?

Fixes #449 

Task summary
made the gmail interface responsive

How to test manually
Fork and clone the repo
open the cloned repo
cd into client
open your terminal in the client folder and run yarn install
then run yarn start
on the browser, navigate to localhost:3000/gmail to view the results
What is the link to the issue on Github?
Issue #449

### CODE REVIEW

**Review by Evavic44 — APPROVED** [review]
LGTM! 👍🏾

**Comment by buka4rill** [comment]
Why am I seeing Vercel app link?

**Comment by Evavic44** [comment]
> Why am I seeing Vercel app link?

@buka4rill Maybe he gave Vercel access to all his repositories. Then it'll generate a link for every PR he makes.

**Comment by chideranwafor** [comment]
@buka4rill, @Evavic44  is right

**Comment by buka4rill** [comment]
ok

**Comment by hokagedemehin** [comment]
Hi @chideranwafor 

You need to change the description on how to test your code

If your code is to make a page responsive, then if we go to the main externaltools link and navigate to that specific page, we should be able to test if it is responsive simply by inspecting the page and changing the viewport size.

The mentors that will mark you, will not use VS code to test your work. They are only working with the live link that is sent with your submission.

Thank you

**Pull request closed without merging**
